### PR TITLE
Added features: Chat-Errors File & Save Classifer file

### PR DESCRIPTION
**Pull request by vveerrgg**
Added the creation / update of a text file feature. The file contains all the messages that were not understood.  Each phrase-message includes the channel and user. 

By seeing which phrases were causing the bot to fail along with where / who was talking to the bot, it makes it a bit easier to improve the custom phrases JSON file.

### CODE REVIEW

**Comment by andrew-templeton** [comment]
Do you want to merge this still?

**Comment by andrew-templeton** [comment]
Added you as a Collaborator, you should have push access now / see if you're able to merge. 
If you do, please alter the package.json to refer to this repo again, instead of the changes made in the last commit to alter URLs.

**Comment by vveerrgg** [comment]
I'll revert package.json back to the core repo.

**Comment by vveerrgg** [comment]
Good to go... lets merge these up.  👍

**Comment by andrew-templeton** [comment]
I'm surprised at how many people ended up using this as the vanilla version / base for their bots, yay! Your addition should make it an even more attractive proposition for people.

**Comment by vveerrgg** [comment]
its' a great stem for launching a bot project.  I've tried to include some of the extended features I've been toying with in my experiments.  Thanks for merging them in.

**Pull request merged**
